package project;

import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import koneksi.koneksi;

public class halamanlogin extends javax.swing.JFrame {
String user,pass;
    private Connection conn=new koneksi().connect();
    public Statement st;
    public ResultSet rs;
    public String username, password, keterangan;
    
    public halamanlogin() {
        initComponents();
    }

        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        bsimpan = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        grs1 = new javax.swing.JSeparator();
        grs2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Sistem Inventaris BGA");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(79, 186, 111));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(228, 228, 228));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setForeground(new java.awt.Color(42, 105, 1));
        jPanel2.setPreferredSize(new java.awt.Dimension(600, 700));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(36, 47, 65));
        jLabel1.setText("PASSWORD");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(36, 47, 65));
        jLabel2.setText("USERNAME");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        txtusername.setBackground(new java.awt.Color(228, 228, 228));
        txtusername.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtusername.setForeground(new java.awt.Color(36, 47, 65));
        txtusername.setText("masukan username");
        txtusername.setBorder(null);
        txtusername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtusernameMouseClicked(evt);
            }
        });
        jPanel2.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 250, 40));

        txtpassword.setBackground(new java.awt.Color(228, 228, 228));
        txtpassword.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtpassword.setText("PasswordPassword");
        txtpassword.setBorder(null);
        txtpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpasswordFocusGained(evt);
            }
        });
        txtpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtpasswordMouseClicked(evt);
            }
        });
        txtpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpasswordKeyPressed(evt);
            }
        });
        jPanel2.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 250, 40));

        bsimpan.setBackground(new java.awt.Color(36, 47, 65));
        bsimpan.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        bsimpan.setForeground(new java.awt.Color(255, 255, 255));
        bsimpan.setText("Login");
        bsimpan.setBorderPainted(false);
        bsimpan.setContentAreaFilled(false);
        bsimpan.setOpaque(true);
        bsimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bsimpanMouseClicked(evt);
            }
        });
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });
        jPanel2.add(bsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 80, -1));

        jButton2.setBackground(new java.awt.Color(36, 47, 65));
        jButton2.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Batal");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setOpaque(true);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 90, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(36, 47, 65));
        jLabel3.setText("BGA Inventaris System");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        grs1.setBackground(new java.awt.Color(36, 47, 65));
        grs1.setForeground(new java.awt.Color(36, 47, 65));
        grs1.setAlignmentX(2.0F);
        grs1.setAlignmentY(2.0F);
        grs1.setPreferredSize(new java.awt.Dimension(3, 3));
        grs1.setRequestFocusEnabled(false);
        jPanel2.add(grs1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 250, -1));

        grs2.setBackground(new java.awt.Color(36, 47, 65));
        grs2.setForeground(new java.awt.Color(36, 47, 65));
        grs2.setAlignmentX(2.0F);
        grs2.setAlignmentY(2.0F);
        grs2.setPreferredSize(new java.awt.Dimension(3, 3));
        grs2.setRequestFocusEnabled(false);
        jPanel2.add(grs2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 250, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/logo.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 70, 70));

        jSeparator9.setBackground(new java.awt.Color(255, 255, 102));
        jSeparator9.setForeground(new java.awt.Color(255, 255, 102));
        jSeparator9.setToolTipText("");
        jSeparator9.setAlignmentX(2.0F);
        jSeparator9.setAlignmentY(2.0F);
        jSeparator9.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        jSeparator9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jSeparator9.setPreferredSize(new java.awt.Dimension(3, 3));
        jSeparator9.setRequestFocusEnabled(false);
        jSeparator9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSeparator9MouseClicked(evt);
            }
        });
        jPanel2.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 10, 10));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("X");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 10, 20, 20));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/userlogin.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/password.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        reset.setBackground(new java.awt.Color(36, 47, 65));
        reset.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        reset.setForeground(new java.awt.Color(255, 255, 255));
        reset.setText("Reset");
        reset.setBorderPainted(false);
        reset.setContentAreaFilled(false);
        reset.setOpaque(true);
        reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetMouseClicked(evt);
            }
        });
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel2.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 80, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(348, 424));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jSeparator9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSeparator9MouseClicked
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_jSeparator9MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        txtusername.setText("");
        txtpassword.setText("");
        txtusername.requestFocus();
    }//GEN-LAST:event_jButton2MouseClicked

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
        String a = txtusername.getText().toString();
        String b = txtpassword.getText().toString();
        try {
            if (txtusername.getText().equals("'*'")
                || txtpassword.getText().equals("'*'")
                || a.contains("'")
                || b.contains("'")) {
                JOptionPane.showMessageDialog(null, "Ada Yang Tidak TerInput / Memakai Tanda Petik", "Error", JOptionPane.ERROR_MESSAGE);
            }
            if (txtusername.getText().equals("") || txtpassword.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Username/Password Tidak Boleh Kosong", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else {
                st = conn.createStatement();
                rs = st.executeQuery("Select * from karyawan where "
                    + "username = '" + txtusername.getText() + "'"
                    + "and password = '" + txtpassword.getText() + "'");
                if (rs.first() == false) {
                    JOptionPane.showMessageDialog(null, "Username, Password, atau Akun Tidak Aktif", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    rs = st.executeQuery("select * from karyawan where username ='"+ txtusername.getText() +"' ");
                    while (rs.next()) {
                        username      = rs.getString("username");
                        keterangan          = rs.getString("keterangan");
                    };
                    s1.setusername(username);
                    s2.setketerangan(keterangan);
                    beranda hu = new beranda(keterangan);
                    JOptionPane.showMessageDialog(null, "Selamat Datang " + s1.getusername(), "Welcome", JOptionPane.INFORMATION_MESSAGE);
                    hu.setVisible(true);
                    this.dispose();
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_bsimpanActionPerformed

    private void bsimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bsimpanMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_bsimpanMouseClicked

    private void txtpasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpasswordKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER) {
            bsimpan.doClick();
        }// TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordKeyPressed

    private void txtpasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpasswordMouseClicked
        // TODO add your handling code here:
        txtpassword.setText("");
    }//GEN-LAST:event_txtpasswordMouseClicked

    private void txtpasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpasswordFocusGained
        // TODO add your handling code here:
        txtpassword.setText("");
    }//GEN-LAST:event_txtpasswordFocusGained

    private void txtusernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtusernameMouseClicked
        // TODO add your handling code here:
        txtusername.setText("");
    }//GEN-LAST:event_txtusernameMouseClicked

    private void resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMouseClicked
        // TODO add your handling code here:
        String sql = "UPDATE karyawan SET `password`=? WHERE username=? ";
        
        try{
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, txtpassword.getText());
            stat.setString(2, txtusername.getText());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null,"pass berhasil diubah");
        } catch (HeadlessException | SQLException e){
             JOptionPane.showMessageDialog(null,"pass berhasil diubah");
        }
    }//GEN-LAST:event_resetMouseClicked

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(halamanlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(halamanlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(halamanlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(halamanlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new halamanlogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bsimpan;
    private javax.swing.JSeparator grs1;
    private javax.swing.JSeparator grs2;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JButton reset;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}

