package project;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;
import java.io.InputStream;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JPanel;
import koneksi.koneksi;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;

/**
 *
 * @author nita
 */
public class laporann extends javax.swing.JFrame {
private Connection conn = new koneksi().connect();
private DefaultTableModel tabmode;
public Statement st;
public ResultSet rs;
    JasperReport jasrep;
    JasperPrint jaspri;
    JasperDesign jasdes;

    public laporann(String keterangan) {
        initComponents();
        selamat();
            
        if (keterangan.equals("Manager")) {
            jkaryawan.setVisible(true);
            jsupplier.setVisible(true);
            jpelanggan.setVisible(true);
            jbarang.setVisible(true);
            jmasuk.setVisible(true);
            jkeluar.setVisible(true);
            jlapor.setVisible(true);
            icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/op.png")));
            
        } else if (keterangan.equals("Admin")) {
            jkaryawan.setVisible(false);
            jsupplier.setVisible(true);
            jpelanggan.setVisible(true);
            jbarang.setVisible(true);
            jmasuk.setVisible(true);
            jkeluar.setVisible(true);
            jlapor.setVisible(true);
            icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/op2.png")));
        }
    }
    

    private laporann() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    public void selamat() {
        try {
            st = conn.createStatement();
            rs = st.executeQuery("select * from karyawan where username = '"+ s1.getusername() +"' and keterangan ='"+ s2.getketerangan() +"' ");
            while (rs.next()) {
                username.setText(rs.getString("nama"));
                keterangan.setText(rs.getString("jabatan"));
            }
        } catch (Exception e) {
        e.printStackTrace();
        }
    }
  

      public void warna (JPanel panel){
        panel.setBackground (new java.awt.Color(204,204,204));
    }
    
    public void hilangwarna (JPanel panel){
        panel.setBackground (new java.awt.Color(243,243,243));
    }
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        bkembali = new javax.swing.JButton();
        jSeparator10 = new javax.swing.JSeparator();
        cetakbarang = new javax.swing.JButton();
        cetakmasuk = new javax.swing.JButton();
        cetakkeluar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cetaklaba = new javax.swing.JButton();
        cetaksupp = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        cetakpelanggan = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        icon = new javax.swing.JLabel();
        jsupplier = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jbarang = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jmasuk = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jkeluar = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jkaryawan = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jlapor = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        keterangan = new javax.swing.JLabel();
        jpelanggan = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Sistem Inventaris BGA");
        setBackground(new java.awt.Color(250, 250, 250));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(250, 250, 250));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel3.setMinimumSize(new java.awt.Dimension(1031, 610));
        jPanel3.setPreferredSize(new java.awt.Dimension(1040, 591));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bkembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/kembali.png"))); // NOI18N
        bkembali.setBorderPainted(false);
        bkembali.setContentAreaFilled(false);
        bkembali.setFocusPainted(false);
        bkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkembaliActionPerformed(evt);
            }
        });
        jPanel3.add(bkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 52, -1));

        jSeparator10.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator10.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        jPanel3.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 1030, 20));

        cetakbarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/cetakstokbrg.png"))); // NOI18N
        cetakbarang.setContentAreaFilled(false);
        cetakbarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cetakbarangMouseClicked(evt);
            }
        });
        jPanel3.add(cetakbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, 120));

        cetakmasuk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/cetakbrgmasuk1.png"))); // NOI18N
        cetakmasuk.setContentAreaFilled(false);
        cetakmasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakmasukActionPerformed(evt);
            }
        });
        jPanel3.add(cetakmasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, -1));

        cetakkeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/cetakbrgkeluar1.png"))); // NOI18N
        cetakkeluar.setContentAreaFilled(false);
        cetakkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakkeluarActionPerformed(evt);
            }
        });
        jPanel3.add(cetakkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 320, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setText("Menu Laporan");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, -1, -1));

        cetaklaba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/cetakpenjualan.png"))); // NOI18N
        cetaklaba.setContentAreaFilled(false);
        cetaklaba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetaklabaActionPerformed(evt);
            }
        });
        jPanel3.add(cetaklaba, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 520, -1, -1));

        cetaksupp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/cetaksuppleir.png"))); // NOI18N
        cetaksupp.setContentAreaFilled(false);
        cetaksupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetaksuppActionPerformed(evt);
            }
        });
        jPanel3.add(cetaksupp, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 530, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("X");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 20, -1, -1));

        jSeparator9.setBackground(new java.awt.Color(255, 255, 102));
        jSeparator9.setForeground(new java.awt.Color(255, 255, 102));
        jSeparator9.setAlignmentX(2.0F);
        jSeparator9.setAlignmentY(2.0F);
        jSeparator9.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        jSeparator9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jSeparator9.setPreferredSize(new java.awt.Dimension(3, 3));
        jSeparator9.setRequestFocusEnabled(false);
        jSeparator9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSeparator9MouseClicked(evt);
            }
        });
        jPanel3.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 30, 20, 10));

        cetakpelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/cetakpelanggan.png"))); // NOI18N
        cetakpelanggan.setContentAreaFilled(false);
        cetakpelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakpelangganActionPerformed(evt);
            }
        });
        jPanel3.add(cetakpelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 1070, 700));

        jPanel1.setBackground(new java.awt.Color(243, 243, 243));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/op.png"))); // NOI18N
        jPanel1.add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jsupplier.setBackground(new java.awt.Color(243, 243, 243));
        jsupplier.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 0, 0, new java.awt.Color(0, 0, 0)));
        jsupplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jsupplierMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jsupplierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jsupplierMouseExited(evt);
            }
        });
        jsupplier.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21.setText("Supplier");
        jLabel21.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsupplier.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jPanel1.add(jsupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 170, 50));

        jbarang.setBackground(new java.awt.Color(243, 243, 243));
        jbarang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 0, 0, new java.awt.Color(0, 0, 0)));
        jbarang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbarangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbarangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbarangMouseExited(evt);
            }
        });
        jbarang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("Data Barang");
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jbarang.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jPanel1.add(jbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 170, 50));

        jmasuk.setBackground(new java.awt.Color(243, 243, 243));
        jmasuk.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 0, 0, new java.awt.Color(0, 0, 0)));
        jmasuk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmasukMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jmasukMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jmasukMouseExited(evt);
            }
        });
        jmasuk.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setText("Barang Masuk");
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        jmasuk.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jPanel1.add(jmasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 170, 50));

        jkeluar.setBackground(new java.awt.Color(243, 243, 243));
        jkeluar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 0, 0, new java.awt.Color(0, 0, 0)));
        jkeluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jkeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jkeluarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jkeluarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jkeluarMouseExited(evt);
            }
        });
        jkeluar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("Barang Keluar");
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jkeluar.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jPanel1.add(jkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 170, 50));

        jkaryawan.setBackground(new java.awt.Color(243, 243, 243));
        jkaryawan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 0, 0, new java.awt.Color(0, 0, 0)));
        jkaryawan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jkaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jkaryawanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jkaryawanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jkaryawanMouseExited(evt);
            }
        });
        jkaryawan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setText("Karyawan");
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        jkaryawan.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 80, -1));

        jPanel1.add(jkaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 170, 50));

        jlapor.setBackground(new java.awt.Color(243, 243, 243));
        jlapor.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 0, 0, new java.awt.Color(0, 0, 0)));
        jlapor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlapor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlaporMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlaporMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlaporMouseExited(evt);
            }
        });
        jlapor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setText("Laporan");
        jLabel23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        jlapor.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jPanel1.add(jlapor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 170, 50));

        username.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        username.setText("Hallo! Mr Kim");
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 100, 23));

        keterangan.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        keterangan.setText("Manager");
        jPanel1.add(keterangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 70, 23));

        jpelanggan.setBackground(new java.awt.Color(243, 243, 243));
        jpelanggan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 0, 0, new java.awt.Color(0, 0, 0)));
        jpelanggan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpelangganMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpelangganMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpelangganMouseExited(evt);
            }
        });
        jpelanggan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 51));
        jLabel24.setText("Pelanggan");
        jLabel24.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpelanggan.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jPanel1.add(jpelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 170, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 700));

        setSize(new java.awt.Dimension(1240, 699));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkembaliActionPerformed
        String ID = s2.getketerangan();
        beranda menu = new beranda(ID);
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bkembaliActionPerformed

    private void jsupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jsupplierMouseClicked
        // TODO add your handling code here:
        String sup = s2.getketerangan();
        supplier menu = new supplier (sup);
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jsupplierMouseClicked

    private void jsupplierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jsupplierMouseEntered
        // TODO add your handling code here:
        warna(jsupplier);
    }//GEN-LAST:event_jsupplierMouseEntered

    private void jsupplierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jsupplierMouseExited
        // TODO add your handling code here:
        hilangwarna(jsupplier);
    }//GEN-LAST:event_jsupplierMouseExited

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel18MouseClicked

    private void jbarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbarangMouseClicked
        // TODO add your handling code here:
        String barang = s2.getketerangan();
        barang menu = new barang (barang);
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbarangMouseClicked

    private void jbarangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbarangMouseEntered
        // TODO add your handling code here:
        warna(jbarang);
    }//GEN-LAST:event_jbarangMouseEntered

    private void jbarangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbarangMouseExited
        // TODO add your handling code here:
        hilangwarna(jbarang);
    }//GEN-LAST:event_jbarangMouseExited

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jmasukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmasukMouseClicked
        String bm = s2.getketerangan();
        barangmasuk menu = new barangmasuk (bm);
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jmasukMouseClicked

    private void jmasukMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmasukMouseEntered
        // TODO add your handling code here:
        warna(jmasuk);
    }//GEN-LAST:event_jmasukMouseEntered

    private void jmasukMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmasukMouseExited
        // TODO add your handling code here:
        hilangwarna(jmasuk);
    }//GEN-LAST:event_jmasukMouseExited

    private void jkeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jkeluarMouseClicked
        String bk = s2.getketerangan();
        barangkeluar menu = new barangkeluar (bk);
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jkeluarMouseClicked

    private void jkeluarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jkeluarMouseEntered
        // TODO add your handling code here:
        warna(jkeluar);
    }//GEN-LAST:event_jkeluarMouseEntered

    private void jkeluarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jkeluarMouseExited
        // TODO add your handling code here:
        hilangwarna(jkeluar);
    }//GEN-LAST:event_jkeluarMouseExited

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        // TODO add your handling code here:
        String absen = s2.getketerangan();
        karyawan menu = new karyawan (absen);
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jkaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jkaryawanMouseClicked
        // TODO add your handling code here:
        String karyawan = s2.getketerangan();
        karyawan menu = new karyawan (karyawan);
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jkaryawanMouseClicked

    private void jkaryawanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jkaryawanMouseEntered
        // TODO add your handling code here:
        warna(jkaryawan);
    }//GEN-LAST:event_jkaryawanMouseEntered

    private void jkaryawanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jkaryawanMouseExited
        // TODO add your handling code here:
        hilangwarna(jkaryawan);
    }//GEN-LAST:event_jkaryawanMouseExited

    private void jlaporMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlaporMouseExited
        // TODO add your handling code here:
        hilangwarna(jlapor);
    }//GEN-LAST:event_jlaporMouseExited

    private void jlaporMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlaporMouseEntered
        // TODO add your handling code here:
        warna(jlapor);
    }//GEN-LAST:event_jlaporMouseEntered

    private void jlaporMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlaporMouseClicked
        String sup = s2.getketerangan();
        laporann menu = new laporann (sup);
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jlaporMouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        // TODO add your handling code here:
        /**String reportSource = null;
        String reportDest = null;

        try {
            Connection koneksi=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory","root","");
            com.mysql.jdbc.Connection c = (com.mysql.jdbc.Connection) koneksi;
            reportSource = System.getProperty("user.dir")+ "/laporan/laporan_data_barang.jrxml";
            reportDest = System.getProperty("user.dir")+ "/laporan/laporan_data_barang.jasper";

            JasperReport jasperReport = JasperCompileManager.compileReport(reportSource);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,null,c);
            JasperExportManager.exportReportToHtmlFile(jasperPrint, reportDest);
            JasperViewer.viewReport(jasperPrint,false);

        } catch(Exception e){
            System.out.println(e);
        }*/
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jSeparator9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSeparator9MouseClicked
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_jSeparator9MouseClicked

    private void cetakbarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cetakbarangMouseClicked
        // TODO add your handling code here:
            try {
            Map hash= new HashMap();
            InputStream imgInputStream = this.getClass().getResourceAsStream("lg.jpg");
           
            hash.put("logo", imgInputStream);
  
            InputStream file = getClass().getResourceAsStream("/laporan/report2.jrxml");
            jasdes = net.sf.jasperreports.engine.xml.JRXmlLoader.load(file);
            jasrep  = net.sf.jasperreports.engine.JasperCompileManager.compileReport(jasdes);
            jaspri   = net.sf.jasperreports.engine.JasperFillManager.fillReport(jasrep,hash,conn);
            JasperViewer.viewReport(jaspri, false);
        }catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_cetakbarangMouseClicked

    private void cetaksuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetaksuppActionPerformed
        try {
            Map hash= new HashMap();
            InputStream imgInputStream = this.getClass().getResourceAsStream("lg.jpg");
            hash.put("logo", imgInputStream);
  
            InputStream file = getClass().getResourceAsStream("/laporan/supplier.jrxml");
            jasdes = net.sf.jasperreports.engine.xml.JRXmlLoader.load(file);
            jasrep  = net.sf.jasperreports.engine.JasperCompileManager.compileReport(jasdes);
            jaspri   = net.sf.jasperreports.engine.JasperFillManager.fillReport(jasrep,hash,conn);
            JasperViewer.viewReport(jaspri, false);
        }catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_cetaksuppActionPerformed

    private void cetakmasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakmasukActionPerformed
        // TODO add your handling code here:
        laporanmasuk mn = new laporanmasuk();
        mn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cetakmasukActionPerformed

    private void cetakkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakkeluarActionPerformed
        laporankeluar mn = new laporankeluar();
        mn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cetakkeluarActionPerformed

    private void cetaklabaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetaklabaActionPerformed
                try {
            Map hash= new HashMap();
            InputStream imgInputStream = this.getClass().getResourceAsStream("lg.jpg");
            hash.put("logo", imgInputStream);
  
            InputStream file = getClass().getResourceAsStream("/laporan/hasiljual.jrxml");
            jasdes = net.sf.jasperreports.engine.xml.JRXmlLoader.load(file);
            jasrep  = net.sf.jasperreports.engine.JasperCompileManager.compileReport(jasdes);
            jaspri   = net.sf.jasperreports.engine.JasperFillManager.fillReport(jasrep,hash,conn);
            JasperViewer.viewReport(jaspri, false);
        }catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_cetaklabaActionPerformed

    private void jpelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpelangganMouseClicked
        // TODO add your handling code here:
        String pelanggan = s2.getketerangan();
        pelanggan menu = new pelanggan (pelanggan);
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jpelangganMouseClicked

    private void jpelangganMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpelangganMouseEntered
        // TODO add your handling code here:
        warna(jpelanggan);
    }//GEN-LAST:event_jpelangganMouseEntered

    private void jpelangganMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpelangganMouseExited
        // TODO add your handling code here:
        hilangwarna(jpelanggan);
    }//GEN-LAST:event_jpelangganMouseExited

    private void cetakpelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakpelangganActionPerformed
        // TODO add your handling code here:                                        
        try {
            Map hash= new HashMap();
            InputStream imgInputStream = this.getClass().getResourceAsStream("lg.jpg");
            hash.put("logo", imgInputStream);
  
            InputStream file = getClass().getResourceAsStream("/laporan/pelanggan.jrxml");
            jasdes = net.sf.jasperreports.engine.xml.JRXmlLoader.load(file);
            jasrep  = net.sf.jasperreports.engine.JasperCompileManager.compileReport(jasdes);
            jaspri   = net.sf.jasperreports.engine.JasperFillManager.fillReport(jasrep,hash,conn);
            JasperViewer.viewReport(jaspri, false);
        }catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_cetakpelangganActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new laporann().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bkembali;
    private javax.swing.JButton cetakbarang;
    private javax.swing.JButton cetakkeluar;
    private javax.swing.JButton cetaklaba;
    private javax.swing.JButton cetakmasuk;
    private javax.swing.JButton cetakpelanggan;
    private javax.swing.JButton cetaksupp;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JPanel jbarang;
    private javax.swing.JPanel jkaryawan;
    private javax.swing.JPanel jkeluar;
    private javax.swing.JPanel jlapor;
    private javax.swing.JPanel jmasuk;
    private javax.swing.JPanel jpelanggan;
    private javax.swing.JPanel jsupplier;
    private javax.swing.JLabel keterangan;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
